# Site settings
author: Chance Smith
title: Falling for Code
header-img: img/home-bg.png
email: chancesmith97@hotmail.com
copyright_name: Chance Smith
description: > # this means to ignore newlines until "baseurl:"
  How I got into coding
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  CRSmith15

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
